export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_FEATURED = 'ADD_FEATURED';
export const FEATURE_PRODUCTS_LOADING = 'FEATURE_PRODUCTS_LOADING';
export const FEATURE_PRODUCTS_FAILED = 'FEATURE_PRODUCTS_FAILED';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const ADD_USER_DATA = 'ADD_USER_DATA';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';