export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_FEATURED = 'ADD_FEATURED';
export const FEATURE_PRODUCTS_LOADING = 'FEATURE_PRODUCTS_LOADING';
export const FEATURE_PRODUCTS_FAILED = 'FEATURE_PRODUCTS_FAILED';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';